version: "3.8"
services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: project.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      # - type: bind
      #   source: /home/ubuntu/certbot/conf/archive
      #   target: /etc/nginx/ssl
      # - /home/ubuntu/certbot/data:/var/www/certbot
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email myemail@google.com --agree-tos --no-eff-email -d domain.com
    volumes:
        - work dir/certbot/conf:/etc/letsencrypt
        - work dir/certbot/logs:/var/log/letsencrypt
        - work dir/certbot/data:/var/www/certbot

volumes:
  static:
  media:
