# Generated by Django 4.0 on 2021-12-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField()),
                ('text', models.TextField()),
                ('tag', models.CharField(max_length=10)),
                ('flag', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=30)),
                ('isBase', models.BooleanField(default=False)),
                ('isStar', models.BooleanField(default=False)),
                ('content', models.JSONField(default=[])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
