# Generated by Django 3.1 on 2022-01-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
