# Generated by Django 3.1 on 2022-01-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20220109_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_blocks', to='service.template', to_field='sub_id'),
        ),
    ]
