# Generated by Django 3.1 on 2022-01-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20220109_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='sub_id',
        ),
    ]
