# Generated by Django 3.1 on 2022-01-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_template_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_templates', to='service.group'),
        ),
    ]
