# Generated by Django 3.1 on 2022-01-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_template_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_templates', to='service.group'),
        ),
    ]
