# Generated by Django 3.1 on 2022-01-10 15:42

import django.core.validators
from django.db import migrations, models
import django_extensions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20220110_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{7}$'), django_extensions.validators.HexValidator(length=7)]),
        ),
    ]
