# Generated by Django 3.1 on 2022-01-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20220111_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetemplate',
            name='tip',
            field=models.CharField(default='', max_length=50),
        ),
    ]
