# Generated by Django 3.1 on 2022-01-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_basetemplate_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetemplate',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
