# Generated by Django 3.1 on 2022-01-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20220124_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
