# Generated by Django 3.1 on 2022-01-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('NULL', 'NULL'), ('GOOGLE', 'GOOGLE')], default='NULL', max_length=10),
        ),
    ]
