# Generated by Django 4.0 on 2022-01-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '사용자의 이메일 주소가 이미 존재합니다.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
